export const TRADES = [
  "Electrician (Inside Wireman)",
  "Electrician (Outside Lineman)",
  "Pipefitter",
  "Welder",
  "Millwright",
  "Carpenter",
  "HVAC Technician",
  "Ironworker",
  "Heavy Equipment Operator",
  "Sheet Metal Worker",
  "Plumber",
  "Boilermaker",
  "Crane Operator",
  "Instrumentation Technician",
  "Insulator",
  "Rigger",
  "Scaffold Builder",
  "Concrete Finisher",
  "Mason / Bricklayer",
  "Painter / Sandblaster",
  "Laborer",
];

export default TRADES;
