name: Supabase Production Migration Sync

on:
  push:
    branches:
      - main

jobs:
  migrate:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
      SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1

      - name: Verify production project ref
        run: |
          if [ "${SUPABASE_PROJECT_REF}" != "kaxlvhqgukmfsy1scxp" ]; then
            echo "Configured project ref does not match the production ref." >&2
            exit 1
          fi

      - name: Link Supabase project
        run: supabase link --project-ref "${SUPABASE_PROJECT_REF}"

      - name: Push Prisma migrations to production
        run: supabase db push --db-url "${SUPABASE_DB_URL}" --non-interactive
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
